language: node_js

sudo: false

notifications:
  email:
  - yiminghe@gmail.com

node_js:
- 12

script:
- |
    if [ "$TEST_TYPE" = test ]; then
      npm test -- --coverage && \
      bash <(curl -s https://codecov.io/bash)
    else
      npm run $TEST_TYPE
    fi

env:
  matrix:
  - TEST_TYPE=lint
  - TEST_TYPE=test
  - TEST_TYPE=coverage
  - TEST_TYPE=compile
